import {
  ActionIcon as NativeActionIcon,
  ActionIconProps as NativeActionIconProps,
  Button as NativeButton,
  ButtonProps as NativeButtonProps,
  Card as NativeCard,
  CardProps as NativeCardProps,
  Fieldset as NativeFieldset,
  FieldsetProps as NativeFieldsetProps,
  Flex as NativeFlex,
  FlexProps as NativeFlexProps,
  Group as NativeGroup,
  GroupProps as NativeGroupProps,
  MultiSelect as NativeMultiSelect,
  MultiSelectProps as NativeMultiSelectProps,
  NumberInput as NativeNumberInput,
  NumberInputProps as NativeNumberInputProps,
  Pill as NativePill,
  PillProps as NativePillProps,
  ScrollArea as NativeScrollArea,
  ScrollAreaProps as NativeScrollAreaProps,
  Text as NativeText,
  TextInput as NativeTextInput,
  TextInputProps as NativeTextInputProps,
  TextProps as NativeTextProps,
} from '@mantine/core'
import { DateInput as NativeDateInput, DateInputProps as NativeDateInputProps } from '@mantine/dates'
import { Dropzone as NativeDropzone, DropzoneProps as NativeDropzoneProps, IMAGE_MIME_TYPE } from '@mantine/dropzone'
import { Link, Redirect, Route, Router, Switch } from 'wouter'

export {
  IMAGE_MIME_TYPE,
  Link,
  NativeActionIcon,
  NativeButton,
  NativeCard,
  NativeDateInput,
  NativeDropzone,
  NativeFieldset,
  NativeFlex,
  NativeGroup,
  NativeMultiSelect,
  NativeNumberInput,
  NativePill,
  NativeScrollArea,
  NativeText,
  NativeTextInput,
  Redirect,
  Route,
  Router,
  Switch,
}

export type {
  NativeActionIconProps,
  NativeButtonProps,
  NativeCardProps,
  NativeDateInputProps,
  NativeDropzoneProps,
  NativeFieldsetProps,
  NativeFlexProps,
  NativeGroupProps,
  NativeMultiSelectProps,
  NativeNumberInputProps,
  NativePillProps,
  NativeScrollAreaProps,
  NativeTextInputProps,
  NativeTextProps,
}
